- README.md
- Headline
- changed to Borderless Coding with logo
- add short description
- Add instructions for running migrations and run Prisma Studio
> docs: adjust README

- src/app/(private)/(routes)/(member)/dashboard/components/forum-widget.tsx
- src/app/(private)/(routes)/(member)/dashboard/components/public-notes-card.tsx
- src/app/(private)/(routes)/(member)/dashboard/page.tsx
- src/components/checklist/index.tsx
- src/components/events-calendar/index.tsx
- src/hooks/checklist/type.ts
- reset challenges according the timestamp and sections
- dashboard responsiveness
- fix small typos
> feat: reset challenges by time

- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
- src/app/(private)/(routes)/(member)/profile/appearance/components/appearance-form.tsx
- src/components/main-logo/index.tsx
- src/components/main-nav/index.tsx
- src/components/mobile-nav/index.tsx
- src/components/top-bar/events-button.tsx
- src/components/top-bar/feedback-button.tsx
- src/components/top-bar/index.tsx
- src/components/top-bar/mobile-button.tsx
- src/components/top-bar/notifications-button/index.tsx
- src/hooks/event/use-event.tsx
- Change toast notification after updating the appearance
- The "recommendation" button does not appear in the navbar, only the feedback button
- In the Dashboard section, clicking the "Share something" link breaks the application
- Fix horizontal dashboard forum widget scroll
> feat: mobile improvements

- src/app/(private)/(routes)/(member)/forum/components/post.tsx
- src/app/api/post/[postId]/route.ts
- update route to user admin delete post
- fix ui of pinned posts
> Fix delete post

- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/forum-feed/use-forum-feed.ts
- src/app/(private)/(routes)/(member)/profile/components/members-list.tsx
- src/components/main-logo/index.tsx
- src/components/main-nav/index.tsx
- Fixed forum feed rendering issues caused by undefined values.
- Improved badge color when the level is undefined or empty.
- Resolved button warning in the main navigation.
- Updated logo based on the resolved theme.
BEFORE
AFTER
> fix: improvements

- package.json
- pnpm-lock.yaml
- prisma/migrations/20240616103146_add_video_order/migration.sql
- prisma/schema.prisma
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/index.tsx
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/use-mentorship-tab.ts
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/page.tsx
- src/app/api/classroom/video/route.ts
- src/components/icons/index.tsx
- add reorder functionality to drag n drop module videos in mentorship video page
> Reorder videos

- src/app/(private)/(routes)/(member)/forum/[postId]/components/forum-comment-component.tsx
- Fix forum comment format date
- Add a tooltip when user hover forum comment timestamp
> fix: forum comment format timestamp

- src/app/(private)/(routes)/(member)/dashboard/components/forum-widget.tsx
- src/app/(private)/(routes)/(member)/forum/components/post.tsx
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/index.tsx
- src/components/short-menu/index.tsx
fixed light-mode problems
remove post-actions from dashboard
> light-mode problems

- src/app/api/webhooks/clerk/route.ts
This PR fixes the handling of clerk's webhook actions on the app, syncing the internal DB from the correct **prismadb** accessor.
> Fix/ Clerk User Image Sync

- src/app/(private)/(routes)/(member)/dashboard/components/timeline-notes.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/page.tsx
- src/app/(private)/(routes)/(member)/profile/components/members-list.tsx
- src/app/(private)/(routes)/(member)/profile/components/personal-info.tsx
- src/app/api/webhooks/clerk/route.ts
This PR adjusts the Clerk's webhook integration with the internal user DB, removes  old github image profile references + UI update at the Post page.
> Refactor: clerk user image sync + UI updates

- prisma/migrations/20240630113124_add_attachments/migration.sql
- prisma/migrations/20240701190852_update_attachments/migration.sql
- prisma/schema.prisma
- src/app/(private)/(routes)/(member)/code-up/components/notes-list.tsx
- src/app/(private)/(routes)/(member)/courses/components/course-card.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/components/post-comments-link.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/components/reply-comment-section/index.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/page.tsx
- src/app/(private)/(routes)/(member)/forum/components/post-likes/index.tsx
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/index.tsx
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/use-mentorship-tab.ts
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/page.tsx
- src/app/(private)/(routes)/(member)/profile/components/members-list.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/index.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/upload-file-module/files-preview.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/upload-file-module/index.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/upload-image-module/index.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/use-new-classroom-video-form.ts
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/page.tsx
- src/app/api/classroom/video/[videoId]/[attachmentId]/route.ts
- src/app/api/classroom/video/[videoId]/route.ts
- src/app/api/classroom/video/route.ts
- src/app/api/uploadthing/core.ts
- src/components/editor/editor.tsx
- src/components/editor/extensions.tsx
- src/lib/types.ts
feat attachments
fix light-mode
fix padding perfil photo
fix height courses
> Light mode

- src/app/(private)/layout.tsx
- src/components/modals/on-boarding-modal/index.tsx
- src/hooks/on-boarding/use-on-boarding.ts
Add on boarding modal with video.
> feat: onboarding modal

- src/app/(private)/(routes)/(member)/forum/[postId]/components/forum-comment-component.tsx
- src/app/(private)/(routes)/(member)/forum/components/post.tsx
- src/app/api/event/route.ts
This PR disables the validation of creating a new community event with unique names + fixes the aspect ratio of user images, mainly in the forum components (post and comment).
> Fix: event register + user image aspect-ratio

- src/app/(private)/(routes)/(member)/mentorship/components/module-carousel/index.tsx
- src/app/(private)/(routes)/(member)/profile/components/personal-info.tsx
- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/index.tsx
- src/components/ui/avatar.tsx
- src/hooks/on-boarding/use-on-boarding.ts
* Fix update user level error 500
* Add more fields on profile page
* Improve transition effect of mentorship page cards
[Evidence](https://www.loom.com/share/18a3d5b5472a4c2f87d886a644a2ed9c?sid=cfe54b41-0a56-4a9f-9c8b-758e0f5be367)
> fix: update user level error

- src/app/(private)/(routes)/admin/users/components/columns.tsx
This PR fixes the aspect-ratio of the user image at the users table
> Fix: fixing user image aspect-ratio at users table

- src/app/(private)/(routes)/admin/courses/[courseId]/components/new-course-form/index.tsx
- src/app/(private)/(routes)/admin/courses/[courseId]/components/new-course-form/use-new-course-form.ts
- src/app/(private)/(routes)/admin/courses/[courseId]/page.tsx
- src/app/api/course/[courseId]/route.ts
handle multiple categories
https://www.loom.com/share/a0672308a9e747ce97aca6e0cf99c2b3
https://www.loom.com/share/64ceaa58462146cd88a62fbc6878409b
> fix: dont show repetead category

- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/post.tsx
- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/use-new-classroom-video-form.ts
- src/app/(private)/(routes)/admin/courses/[courseId]/components/new-course-form/index.tsx
- src/app/(private)/(routes)/admin/courses/[courseId]/components/new-course-form/use-new-course-form.ts
- src/app/api/post/[postId]/likes/route.ts
- src/app/api/post/[postId]/pin/route.ts
- src/app/api/post/[postId]/route.ts
- src/app/api/uploadthing/core.ts
- src/components/ui/toast.tsx
- src/components/ui/use-toast.ts
handle error for max file size on ui
show 3 most liked posts as pinned in category === all
remove console.logs
> Max file size error

- src/app/(private)/(routes)/(member)/forum/[postId]/opengraph-image.tsx
add image component to display metadata
> feat: component to display image with metadata

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
> feat: Head meatdata

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
> Test metadata

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
> feat: add head

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/opengraph-image.tsx
> feat: open graph image

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/opengraph-image.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
- src/app/layout.tsx
remove default metadata, maybe overriding dynamic metadata for post
> feat: test maybe default one overriding the dynamic metadata

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/opengraph-image.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
> feat: add url

- src/app/(private)/(routes)/(member)/forum/[postId]/opengraph-image.tsx
- src/app/layout.tsx
> feat: opengraph

- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
- src/app/layout.tsx
> feat: remove default metadata

- src/app/(private)/(routes)/admin/classroom/(routes)/video/[videoId]/components/new-classroom-video-form/upload-file-module/index.tsx
- src/app/api/uploadthing/core.ts
> fix: files

- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/comments/comment-component.tsx
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/comments/use-comments.ts
This PR fixes the bug that is responsible for not showing the correct use profile picture in the mentorship video comments.
> Fix: profile pic at mentorship video comments

- prisma/migrations/20240909211834_add_cascade_on_delete/migration.sql
- prisma/migrations/20240909212203_add_cascade_on_delete_cat/migration.sql
- prisma/migrations/20240909220752_default_id_category/migration.sql
- prisma/migrations/20240917143327_add_discord_webhook_id_in_post/migration.sql
- prisma/schema.prisma
- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/index.tsx
- src/app/api/post/[postId]/route.ts
- src/app/api/post/route.ts
- src/lib/casl/ability.ts
- src/lib/casl/entities/mentorship.ts
- src/lib/casl/subjects/index.ts
This PR adds the discord webhook integration feature, to trigger bot messages at the General discord channel of the community when a user creates a new Post in the community. It also updates the post URL in the bot message if the user performs an update on the post title.
- Opengraph images are missing in prints due to the development environment.
> feat: discord webhook integration

- src/app/(private)/(routes)/(member)/forum/components/create-post.tsx
- src/app/(private)/(routes)/(member)/forum/components/filters/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/filters/use-forum-filters.ts
- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/forum-feed/use-forum-feed.ts
- src/app/(private)/(routes)/(member)/profile/components/image-input.tsx
- src/app/(private)/(routes)/(member)/profile/components/personal-info.tsx
- src/app/api/post/route.ts
- src/components/ui/input.tsx
- src/hooks/post/use-post.ts
- src/hooks/shared/use-debounce-search.ts
This pull request introduces a search bar functionality to the forum page, enabling users to locate relevant posts quickly. Additionally, it enhances the Input component by implementing a new `clearable` feature. Ignore password managers for doing unwanted autofill inputs on the profile page.
📹 Demo: https://www.loom.com/share/82d887e91bac43e29429b08985bbfbf9?sid=86088757-9e8d-4d71-be4e-e02fe9b27cd4
Demo 2: https://www.loom.com/share/224ee80188b14cc8ab46beb9c5d20bd6?sid=943aac05-5db2-4bb5-8807-dea0d03dbfbc
> feat: add forum search bar

- src/app/(private)/(routes)/(member)/forum/components/rich-text-input-post/index.tsx
- Before wasn't allowing to write in title field, this pr fix this
> fix: allow to write in title field

- src/app/(private)/(routes)/(member)/forum/components/edit-post-form/index.tsx
A similar fix was added into staging, not main, but fix the creating modal, this one fix the edit modal
> fix: edit title

- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/index.tsx
- src/app/(private)/(routes)/(member)/mentorship/components/module-carousel/index.tsx
- button to start/stop dragging 
- bigger height and show 2 modules in mobile screen
- https://www.loom.com/share/4612de5daea64eb58706c7d644105bad
> Small improvments

- src/app/(private)/(routes)/(member)/interests/components/InterestModal.tsx
- src/app/(private)/(routes)/(member)/interests/components/interestsComponent.tsx
- src/app/(private)/(routes)/(member)/interests/page.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/SocialLinks.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/UserInterests.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/useFollowersAndFollowings.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/useUserInterests.ts
- src/app/(private)/(routes)/(member)/user/[userName]/page.tsx
- src/app/(private)/(routes)/admin/interests/[interestId]/components/new-interest-form/use-new-interest-form.ts
- src/app/api/interest/[interestId]/[userId]/route.tsx
- src/app/api/interest/[interestId]/route.ts
- src/app/api/interest/user/[userId]/route.ts
- src/app/api/user/follow/route.ts
- src/components/icons/index.tsx
- src/lib/constants.tsx
https://www.loom.com/share/f1af73d2e99b40de91271be806918e04
Interests page
Interests Admin page
Add Interests in user profile page
Add follow/unfollow logic
> Interest follow

- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
This PR updates the loading component for the forum posts infinity scroll, from a simple spinner to skeletons with the post layout.
> Refactor: Forum posts loading skeleton

- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/SocialLinks.tsx
- Fix incorrect shadow in light mode on users page
- Adjust social links icons size
> fix(user-page): incorrect shadow in light mode

- src/components/app-sidebar/index.tsx
This PR adjusts sidebar component responsive styles and also adds hover styles for the sidebar items
> Refactor: adjusting sidebar mobile UI + hover styles

- src/app/(private)/(routes)/(member)/dashboard/components/public-notes-card.tsx
- src/app/(private)/(routes)/(member)/dashboard/components/timeline-notes-content.tsx
- src/app/(private)/(routes)/(member)/dashboard/components/timeline-notes.tsx
- src/app/(private)/(routes)/(member)/dashboard/page.tsx
- src/app/(private)/(routes)/(member)/interests/components/interestsComponent.tsx
- src/app/(private)/(routes)/(member)/profile/layout.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/UserInterests.tsx
- src/lib/constants.tsx
https://www.loom.com/share/b89b9ea44cd7474a9bb3ce709e89e83b
- show colored badges 
- public profile tab in public settings
- improve timeline for notes
> Profile improvements

- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
Fix profile user role badge on mobile
> Fix: profile user role badge mobile

- src/components/app-sidebar/index.tsx
- src/components/main-logo/index.tsx
- src/components/ui/sidebar.tsx
Fix: sidebar was inconsistent in mentorship page
> Fix sidebar

- src/app/(auth)/(routes)/sign-in/[[...sign-in]]/components/user-auth-form/use-user-auth-form.ts
This pull request removes the `userData` parameter from the sign-in process in compliance with recent privacy updates from Clerk.
> Remove userData from Sign-In for Clerk Privacy Compliance

- src/app/(private)/(routes)/(member)/dashboard/components/forum-widget.tsx
- src/app/(private)/(routes)/(member)/dashboard/components/public-notes-card.tsx
- src/app/(private)/(routes)/(member)/dashboard/components/public-notes-content.tsx
- src/app/(private)/(routes)/(member)/dashboard/page.tsx
- src/components/events-calendar/index.tsx
- src/components/top-bar/index.tsx
Enhances the dashboard layout and improves the scrolling behavior of the `ForumWidget` and `PublicNotesCard` components.
1. Adjusted the layout of the dashboard to ensure equal height columns for `ForumWidget` and `EventsCalendar`/`PublicNotesCard`.
2. Implemented responsive height limits for scroll areas in `ForumWidget` and `PublicNotesContent`.
3. Improved scrollbar positioning to prevent overlap with content.
- Modified `page.tsx` in the dashboard to use flex layout for equal height columns.
- Updated `forum-widget.tsx` and `public-notes-content.tsx` with new ScrollArea configurations.
- Added `h-[calc(100vh-20rem)] max-h-[30rem]` classes to ScrollArea components for responsive height.
- Implemented `pr-4 -mr-4` technique to position scrollbars away from content.
These changes enhance …
> Improve Dashboard Layout and Scrolling Behavior

- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-header/index.tsx
- src/components/app-sidebar/index.tsx
- src/components/default-layout/index.tsx
- src/components/user-button/index.tsx
> feat: add menu for user actions

- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/admin/users/components/columns.tsx
- src/app/(private)/(routes)/admin/users/components/user-cell-roles.tsx
- src/lib/utils.ts
This PR adds a utility function that returns the user's roles based on a priority order, the main usage is at the user's public profile role tag and user's CMS table.
> refactor: adding getHighestPriorityRole function + applying it

- src/app/api/user/route.ts
- src/components/default-layout/index.tsx
- Always set the username when updating the user
- if the username is not in clerk, fetch the username from db
> Fix sidebar username

- src/app/(private)/(routes)/(member)/forum/components/post.tsx
This pull request introduces a new hover effect for forum posts, enhancing user interaction and visual feedback.
- Implemented a hover effect on forum posts using the primary color from the palette to improve user experience and engagement.
https://github.com/user-attachments/assets/e4f32ab7-76e2-4d06-a397-659543547375
> Add Hover Effect to Forum Posts

- src/app/api/uploadthing/core.ts
- src/components/editor/use-image-upload.tsx
Increase the upload max size for files to 256MB.
> Increase file upload max size

- src/app/(private)/(routes)/(member)/mentorship/components/mentorship-sections/index.tsx
https://www.loom.com/share/374db862cebb488d95a41710eed6f767
> feat: toogle dragging button

- src/app/(private)/(routes)/(member)/courses/components/course-filter-options.tsx
- src/app/(private)/(routes)/(member)/courses/components/courses-content.tsx
- src/hooks/course/use-course-filter-options.ts
https://www.loom.com/share/2573097110dd49259002f09a768ebde8
> Improve filters courses

- src/components/default-layout/index.tsx
- src/components/top-bar/index.tsx
- src/hooks/use-mobile.tsx
- src/styles/globals.css
https://www.loom.com/share/7849682647d645c590728ae0909f86ca
> Fix main width md screens

- src/app/api/search/route.ts
- src/components/top-bar/search-dialog/ResultComponents.tsx
- src/components/top-bar/search-dialog/utils.ts
- src/hooks/search/types.ts
Add modules and videos to search, and remove classroom
https://www.loom.com/share/96d9aed85bcf48319794da208ee1e9d1
> Improve search results

- src/app/(private)/(routes)/(member)/user/[userName]/page.tsx
> Create post component user page

- src/components/ui/dialog.tsx
https://www.loom.com/share/2179fa6a1b51443db665a04f980c9cc6
> Fix unresposible screen after delete post

- src/app/(private)/(routes)/admin/courses/components/columns.tsx
- src/app/(private)/(routes)/admin/courses/components/courses-client.tsx
This PR fixes the courses table overflow on the courses CMS page. It also adds a maximum width for the courses URL table cell with the truncated style when too long.
https://share.cleanshot.com/pHWjpLG0
> fix: fixing course cms table overflow + course url truncate

- src/app/(private)/(routes)/(member)/dashboard/components/forum-widget.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/[...titleSlug]/page.tsx
- src/app/(private)/(routes)/(member)/forum/[postId]/components/forum-comment-component.tsx
- src/app/(private)/(routes)/(member)/forum/components/forum-feed/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/post-likes/index.tsx
- src/app/(private)/(routes)/(member)/forum/components/post-likes/use-post-likes.ts
- src/app/(private)/(routes)/(member)/forum/components/post.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/UserPosts.tsx
- src/app/(private)/(routes)/(member)/user/[userName]/components/score-activity/use-score-activity.ts
- src/app/(private)/(routes)/(member)/user/[userName]/page.tsx
- src/hooks/post/use-post.ts
- src/hooks/scoreboard/use-scoreboard.ts
https://trello.com/c/EwfxpaGc/150-melhoria-no-public-profile-ao-dar-like-no-post-deve-dar-refetch-na-contagem-de-pontos-do-user-verificar-usequery-dos-pontos
> Refetch score points on like

- src/app/(private)/(routes)/(member)/code-breakers/constants/exercises.ts
> fix: fix problem link

- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/index.tsx
- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/use-new-user-form.ts
This PR adds the "Learning Path" selector for the Users CMS form, for the Admins.
> Feat: edit trail for users cms

- src/app/(private)/(routes)/(member)/forum/components/rich-text-input-post/index.tsx
- src/components/editor/editor.tsx
This PR includes updates to fix the user interface and functionality of the rich text editor in the forum post creation flow and in the code-up creation.
- Create post `rich-text-input`, not expanding width anymore
- Bubble menu not glitching its position at code-up
> Fix: small fixes

- package.json
- pnpm-lock.yaml
- src/app/(private)/(routes)/(member)/forum/[postId]/components/send-comment-button.tsx
- src/app/(private)/(routes)/(member)/leaderboard/page.tsx
- src/components/leaderboard/infinite-leaderboard-empty-state.tsx
- src/components/leaderboard/top-three.tsx
- tailwind.config.js
> Fix: Leaderboard top three carousel

- src/app/(private)/(routes)/(member)/mentorship/[videoId]/components/mentorship-tab/use-mentorship-tab.ts
- src/app/(private)/(routes)/(member)/mentorship/components/mentorship-sections/index.tsx
https://trello.com/c/ktOMKniz/156-bug-problema-de-estado-ui-ao-tentar-alterar-a-ordem-dos-modulos-da-mentorship-ao-clicar-em-stop-dragging-a-ui-ainda-aparece-como
> Fix mentorship dragger

- src/app/(auth)/(routes)/sign-in/[[...sign-in]]/components/user-auth-form/use-user-auth-form.ts
- src/app/api/user/[userId]/remove-username-cookie/route.ts
- src/app/api/user/[userId]/set-username-cookie/route.ts
- src/components/app-sidebar/components/sidebar-footer.tsx
- src/components/default-layout/ensureUsernameCookie.ts
- src/components/default-layout/index.tsx
- src/components/top-bar/logout-button.tsx
https://trello.com/c/Isozs5Nz/144-add-retry-method-when-the-await-currentuser-returns-an-error
> Avoid call current user

- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
This PR fixes the `staleTime` prop of the PointsStat component, in the user's public profile.
> fix: fixing user profile points popover data staleTime

- package.json
- pnpm-lock.yaml
- prisma/migrations/20250728002552_add_referral_credits_balance/migration.sql
- prisma/schema.prisma
- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/index.tsx
- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/use-new-user-form.ts
- src/app/(private)/(routes)/admin/users/components/columns.tsx
- src/app/api/user/route.ts
- src/components/icons/index.tsx
- src/components/ui/currency-input.tsx
This PR introduces a "Referral Credits Balance" feature for users, with database schema updates, backend API changes, and frontend enhancements. Changes include: adding the new field to the database and user model, updating the user management form and API endpoints, and enhancing the user profile UI to display referral credit information.
> Feat: referral system temp

- src/app/(private)/(routes)/(member)/user/[userName]/components/Header.tsx
- src/app/(private)/(routes)/admin/users/[userId]/components/new-user-form/index.tsx
[Release Notes 1.3.6](https://github.com/ProgramadoresSemPatria/sem-patria-community/releases/tag/1.3.6)
> [HOTFIX] Release/Referral Credits Balance
